# Generated by Django 5.2.10 on 2026-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdspecies',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
