# Generated by Django 5.2.10 on 2026-02-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_birdspecies_is_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdspecies',
            name='district',
        ),
        migrations.RemoveField(
            model_name='birdspecies',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='birdspecies',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='birdspecies',
            name='longitude',
        ),
        migrations.CreateModel(
            name='BirdLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.birdspecies')),
            ],
        ),
    ]
