# Generated by Django 5.2.10 on 2026-02-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_birdspecies_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdspecies',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
